# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: ZnPdCo
google_analytics: ZnPdCo
title: ZnPdCo 的博客

kramdown:
  math_engine: null

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ZnPdCo

description: ZnPdCo 的博客
author:
  name: ZnPdCo
  email: poiuytreertyuiop@outlook.com
  github: ZnPdCo
  bio: MLE
  icon: https://cdn.luogu.com.cn/upload/image_hosting/zzlxiek3.png

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
